/**
 * The food-card SQL shared by the seed migration generator and the sync
 * script: upsert every card in data/food-cards/cards.jsonl, then make each
 * card's `food_card_vectors` strings match its current definition (row
 * name_en / name_primary, card food and sentence, EN aliases, VI names) —
 * retired strings are deleted, new ones inserted with a NULL embedding for
 * scripts/db/backfill_card_embeddings.ts. Cards whose composition row does not
 * exist yet are skipped, so the SQL applies to any environment and is safe to
 * re-run.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

export const SOURCE = 'data/food-cards/cards.jsonl';
const CHUNK = 500;
const FACETS = [
  'part_cut',
  'form_processing',
  'cooking_method',
  'fat_level',
  'brand',
] as const;

interface Card {
  id: string;
  food: string;
  aliases_en: string[];
  names_vi: string[];
  card: string;
  [facet: string]: unknown;
}

const lit = (s: string) => `'${s.replaceAll("'", "''")}'`;
const arr = (xs: string[]) =>
  `ARRAY[${xs.map((x) => lit(x.trim())).join(', ')}]::text[]`;
const facet = (v: unknown) =>
  typeof v === 'string' && v.trim() && v.trim().toLowerCase() !== 'none'
    ? lit(v.trim())
    : 'NULL';

/** Every string that names a card, as a SQL set expression over `c` and `f`. */
const CARD_STRINGS = `unnest(
  ARRAY[f."name_en", f."name_primary", c."food", c."card"] || c."aliases_en" || c."names_vi"
) AS t(text)`;

export function buildCardSql(): { sql: string; cards: number; sha: string } {
  const raw = readFileSync(SOURCE, 'utf8');
  const cards: Card[] = raw
    .split('\n')
    .filter(Boolean)
    .map((l) => JSON.parse(l));
  const sha = createHash('sha256').update(raw).digest('hex');

  const values = cards.map((c) => {
    const aliases = (c.aliases_en ?? []).filter((s) => s?.trim());
    const namesVi = (c.names_vi ?? []).filter((s) => s?.trim());
    return `(${[
      lit(c.id),
      lit(c.food.trim()),
      arr(aliases),
      arr(namesVi),
      ...FACETS.map((f) => facet(c[f])),
      lit(c.card.trim()),
    ].join(', ')})`;
  });

  const inserts: string[] = [];
  for (let i = 0; i < values.length; i += CHUNK) {
    inserts.push(`INSERT INTO "food_cards" (
  "food_composition_id", "food", "aliases_en", "names_vi", "part_cut",
  "form_processing", "cooking_method", "fat_level", "brand", "card"
)
SELECT v.* FROM (VALUES
${values.slice(i, i + CHUNK).join(',\n')}
) AS v(food_composition_id, food, aliases_en, names_vi, part_cut,
       form_processing, cooking_method, fat_level, brand, card)
WHERE EXISTS (
  SELECT 1 FROM "vietnamese_food_composition" f WHERE f."id" = v.food_composition_id
)
ON CONFLICT ("food_composition_id") DO UPDATE SET
  "food" = EXCLUDED."food",
  "aliases_en" = EXCLUDED."aliases_en",
  "names_vi" = EXCLUDED."names_vi",
  "part_cut" = EXCLUDED."part_cut",
  "form_processing" = EXCLUDED."form_processing",
  "cooking_method" = EXCLUDED."cooking_method",
  "fat_level" = EXCLUDED."fat_level",
  "brand" = EXCLUDED."brand",
  "card" = EXCLUDED."card";`);
  }

  const sql = `SET search_path TO public, extensions;

-- Food cards generated by scripts/data/food-cards/card-sql.ts
-- Source: ${SOURCE} (${cards.length} cards, sha256 ${sha})
-- Curated with Opus (rewrite + independent audit); nutrients are never edited.
-- Embeddings are intentionally omitted: scripts/db/backfill_card_embeddings.ts
-- fills food_card_vectors.embedding (the prod deploy runs it automatically).

${inserts.join('\n\n')}

-- Strings a card no longer has (an alias removed, a card sentence rewritten).
DELETE FROM "food_card_vectors" v
USING "food_cards" c
JOIN "vietnamese_food_composition" f ON f."id" = c."food_composition_id"
WHERE v."food_composition_id" = c."food_composition_id"
  AND NOT EXISTS (
    SELECT 1 FROM ${CARD_STRINGS}
    WHERE btrim(t.text) = v."text"
  );

-- Every string that names a card, one vector row each (max-sim retrieval).
INSERT INTO "food_card_vectors" ("food_composition_id", "text")
SELECT DISTINCT c."food_composition_id", btrim(t.text)
FROM "food_cards" c
JOIN "vietnamese_food_composition" f ON f."id" = c."food_composition_id"
CROSS JOIN LATERAL ${CARD_STRINGS}
WHERE t.text IS NOT NULL AND btrim(t.text) <> ''
ON CONFLICT ("food_composition_id", "text") DO NOTHING;
`;
  return { sql, cards: cards.length, sha };
}
