/**
 * Every page and route handler under `app/`, as the URL pattern Next serves
 * it at: route groups `(…)` dropped, dynamic segments kept as `[name]` /
 * `[...name]`. DATA ONLY — `route-template.ts` matches outgoing URLs against
 * it so a segment in a dynamic position is always redacted, whatever it
 * happens to be spelled like.
 *
 * Checked against the filesystem by `__tests__/route-template.test.ts`: add
 * or remove a `page.tsx` / `route.ts` and that test fails until this list is
 * updated. (The standalone image does not ship `app/`, so it cannot be read
 * at runtime.)
 */
export const APP_ROUTE_PATTERNS = [
  '/',
  '/.well-known/oauth-protected-resource',
  '/[locale]',
  '/[locale]/[...rest]',
  '/[locale]/activity',
  '/[locale]/admin',
  '/[locale]/admin/feedback',
  '/[locale]/admin/feedback/[id]',
  '/[locale]/admin/health',
  '/[locale]/admin/prompts',
  '/[locale]/admin/prompts/[name]',
  '/[locale]/admin/requests',
  '/[locale]/admin/requests/[id]',
  '/[locale]/circle',
  '/[locale]/circle/[shareId]',
  '/[locale]/circle/friends',
  '/[locale]/circle/g/[groupId]',
  '/[locale]/dashboard',
  '/[locale]/design-system',
  '/[locale]/docs/[...slug]',
  '/[locale]/invite/[slug]',
  '/[locale]/logging',
  '/[locale]/nutrition',
  '/[locale]/onboarding',
  '/[locale]/pricing',
  '/[locale]/reset-password',
  '/[locale]/settings',
  '/api/[...unmatched]',
  '/api/analyze-meal',
  '/api/analyze-meal/debug',
  '/api/auth/send-email',
  '/api/csp-report',
  '/api/healthz',
  '/api/og/macro-card/[shareId]',
  '/api/supabase-proxy/[...path]',
  '/api/v1/account',
  '/api/v1/account/billing-config',
  '/api/v1/account/entitlements',
  '/api/v1/account/entitlements/reconcile',
  '/api/v1/auth/apple/token',
  '/api/v1/barcode/log',
  '/api/v1/barcode/search',
  '/api/v1/chat-groups',
  '/api/v1/chat-groups/[groupId]',
  '/api/v1/chat-groups/[groupId]/feed',
  '/api/v1/chat-groups/[groupId]/leave',
  '/api/v1/chat-groups/[groupId]/members',
  '/api/v1/chat-groups/[groupId]/members/[userId]',
  '/api/v1/chat-groups/[groupId]/messages',
  '/api/v1/dashboard',
  '/api/v1/dashboard/heatmap',
  '/api/v1/feedback',
  '/api/v1/feedback/screenshot',
  '/api/v1/groups/feed',
  '/api/v1/groups/friends',
  '/api/v1/groups/friends/block',
  '/api/v1/groups/friends/blocked',
  '/api/v1/groups/friends/feed',
  '/api/v1/groups/friends/read-marker',
  '/api/v1/groups/friends/remove',
  '/api/v1/groups/friends/unblock',
  '/api/v1/groups/invite/[slug]',
  '/api/v1/groups/invite/accept',
  '/api/v1/groups/invites',
  '/api/v1/groups/invites/accept',
  '/api/v1/groups/invites/accept-cheat',
  '/api/v1/groups/invites/dismiss',
  '/api/v1/groups/meal-share',
  '/api/v1/groups/profile',
  '/api/v1/groups/profile/avatar',
  '/api/v1/groups/profile/name',
  '/api/v1/groups/shares',
  '/api/v1/groups/shares/[shareId]',
  '/api/v1/groups/shares/log',
  '/api/v1/groups/shares/reaction',
  '/api/v1/groups/shares/reply',
  '/api/v1/ingredients/search',
  '/api/v1/logging/day',
  '/api/v1/logging/day/complete',
  '/api/v1/meals',
  '/api/v1/meals/[mealId]',
  '/api/v1/meals/[mealId]/duplicate',
  '/api/v1/meals/cheat-occasions',
  '/api/v1/meals/cheat-repeat',
  '/api/v1/meals/confirm',
  '/api/v1/meals/dates',
  '/api/v1/meals/manual',
  '/api/v1/meals/pending',
  '/api/v1/meals/pending/[analysisId]',
  '/api/v1/meals/relog',
  '/api/v1/meals/relog/candidates',
  '/api/v1/meals/relog/stage',
  '/api/v1/notifications',
  '/api/v1/notifications/badge',
  '/api/v1/notifications/push-tokens',
  '/api/v1/notifications/read',
  '/api/v1/notifications/seen',
  '/api/v1/nutrition-label/images/[imageId]',
  '/api/v1/nutrition-label/log',
  '/api/v1/nutrition-label/scan',
  '/api/v1/nutrition/candidates',
  '/api/v1/nutrition/overview',
  '/api/v1/onboarding/nudge/minimize',
  '/api/v1/onboarding/nudge/restore',
  '/api/v1/onboarding/profile',
  '/api/v1/onboarding/screen',
  '/api/v1/profile',
  '/api/v1/profile/sharing',
  '/api/v1/reports',
  '/api/v1/waitlist',
  '/api/v1/waitlist/confirm',
  '/api/v1/weight',
  '/api/v1/weight/[loggedDate]',
  '/api/v1/weight/summary',
  '/api/webhooks/revenuecat',
  '/auth/callback',
  '/auth/verify',
  '/llms.txt',
  '/md/[locale]/[...slug]',
  '/openapi.json',
] as const;

/**
 * File-convention metadata routes (`robots.ts`, `sitemap.ts`, `manifest.ts`,
 * `favicon.ico`) — served at fixed paths with no page or route file.
 */
export const APP_METADATA_PATHS = [
  '/robots.txt',
  '/sitemap.xml',
  '/manifest.webmanifest',
  '/favicon.ico',
] as const;
