import type { ConceptId } from '../types';

/** Bare generic words clarify on exact match and never enter folded lookup. */
export const AMBIGUOUS = 'AMBIGUOUS' as const;
export type ConceptResolution = ConceptId | typeof AMBIGUOUS;

/**
 * Normalized surface form → concept id, or the deliberate AMBIGUOUS sentinel.
 * Keep generic words ambiguous; add only qualified, unambiguous aliases to a
 * concrete concept. The resolver separately rejects folded collisions.
 */
export const ALIAS_TO_CONCEPT: Record<string, ConceptResolution> = {
  'bánh bao': 'banh-bao',
  'banh bao': 'banh-bao',
  'bánh bao nhân thịt': 'banh-bao',
  'bánh bao trứng cút': 'banh-bao',
  'trứng cút': 'quail-egg',
  'trứng chim cút': 'quail-egg',
  'quail egg': 'quail-egg',
  'bánh mì': 'banh-mi-loaf',
  'bánh mỳ': 'banh-mi-loaf',
  'ức gà': 'chicken-breast',
  'uc ga': 'chicken-breast',
  'chicken breast': 'chicken-breast',
  'đùi gà': 'chicken-thigh',
  'chicken thigh': 'chicken-thigh',
  'chicken drumstick': 'chicken-thigh',
  'cánh gà': 'chicken-wing',
  'chicken wing': 'chicken-wing',
  'sườn heo': 'rib-piece',
  'sườn bò': 'rib-piece',
  'sườn dê': 'rib-piece',
  'sườn cừu': 'rib-piece',
  'pork rib': 'rib-piece',
  'beef rib': 'rib-piece',
  'goat rib': 'rib-piece',
  'lamb rib': 'rib-piece',
  'cá nguyên con': 'whole-fish',
  'nguyên con cá': 'whole-fish',
  'con cá': 'whole-fish',
  '1 con cá': 'whole-fish',
  'whole fish': 'whole-fish',
  'khúc cá': 'fish-section',
  'khoanh cá': 'fish-section',
  'fish steak': 'fish-section',
  'fish section': 'fish-section',
  'phi lê cá': 'fish-fillet',
  'cá phi lê': 'fish-fillet',
  'miếng cá': 'fish-fillet',
  'fish fillet': 'fish-fillet',
  'boneless fish piece': 'fish-fillet',
  'tôm nguyên vỏ': 'shell-on-shrimp',
  'tôm còn vỏ': 'shell-on-shrimp',
  'shell-on shrimp': 'shell-on-shrimp',
  'shell on shrimp': 'shell-on-shrimp',
  'tôm bóc vỏ': 'peeled-shrimp',
  'tôm lột vỏ': 'peeled-shrimp',
  'peeled shrimp': 'peeled-shrimp',
  ghẹ: 'whole-crab',
  cua: 'whole-crab',
  'cua nguyên con': 'whole-crab',
  'ghẹ nguyên con': 'whole-crab',
  'whole crab': 'whole-crab',
  'thịt cua': 'picked-crab-meat',
  'thịt ghẹ': 'picked-crab-meat',
  'picked crab meat': 'picked-crab-meat',
  'crab meat': 'picked-crab-meat',
  'trứng gà nguyên vỏ': 'egg-in-shell',
  'trứng gà còn vỏ': 'egg-in-shell',
  'egg in shell': 'egg-in-shell',
  'trứng gà luộc': 'peeled-egg',
  'trứng luộc': 'peeled-egg',
  'trứng gà bóc vỏ': 'peeled-egg',
  'trứng gà': 'peeled-egg',
  'chicken egg': 'peeled-egg',
  'boiled egg': 'peeled-egg',
  'peeled egg': 'peeled-egg',
  'nem lụi': 'nem-lui',
  'nem lui': 'nem-lui',
  'nem lụi nướng': 'nem-lui',
  'phần protein áp chảo': 'pan-seared-protein-serving',
  'pan-seared protein serving': 'pan-seared-protein-serving',
  cơm: 'cooked-rice',
  'cơm trắng': 'cooked-rice',
  'mì gói': 'instant-noodle-pack',
  'mi goi': 'instant-noodle-pack',
  'mì tôm': 'instant-noodle-pack',
  'mi tom': 'instant-noodle-pack',
  'mì ăn liền': 'instant-noodle-pack',
  'mi an lien': 'instant-noodle-pack',
  'instant noodles': 'instant-noodle-pack',
  'instant noodle': 'instant-noodle-pack',
  bánh: AMBIGUOUS,
  bun: AMBIGUOUS,
  slice: AMBIGUOUS,
  bowl: AMBIGUOUS,
  rice: AMBIGUOUS,
  bread: AMBIGUOUS,
};
