/**
 * Country list for onboarding and settings.
 * Sorted alphabetically by English name. Vietnamese name shown as hint.
 * value = ISO 3166-1 English short name (stored in DB).
 */
export const COUNTRIES = [
  { value: 'Afghanistan', vi: 'Afghanistan', flag: '🇦🇫' },
  { value: 'Argentina', vi: 'Argentina', flag: '🇦🇷' },
  { value: 'Australia', vi: 'Úc', flag: '🇦🇺' },
  { value: 'Austria', vi: 'Áo', flag: '🇦🇹' },
  { value: 'Bangladesh', vi: 'Bangladesh', flag: '🇧🇩' },
  { value: 'Belgium', vi: 'Bỉ', flag: '🇧🇪' },
  { value: 'Brazil', vi: 'Brazil', flag: '🇧🇷' },
  { value: 'Cambodia', vi: 'Campuchia', flag: '🇰🇭' },
  { value: 'Canada', vi: 'Canada', flag: '🇨🇦' },
  { value: 'Chile', vi: 'Chile', flag: '🇨🇱' },
  { value: 'China', vi: 'Trung Quốc', flag: '🇨🇳' },
  { value: 'Colombia', vi: 'Colombia', flag: '🇨🇴' },
  { value: 'Czech Republic', vi: 'Séc', flag: '🇨🇿' },
  { value: 'Denmark', vi: 'Đan Mạch', flag: '🇩🇰' },
  { value: 'Egypt', vi: 'Ai Cập', flag: '🇪🇬' },
  { value: 'Finland', vi: 'Phần Lan', flag: '🇫🇮' },
  { value: 'France', vi: 'Pháp', flag: '🇫🇷' },
  { value: 'Germany', vi: 'Đức', flag: '🇩🇪' },
  { value: 'Greece', vi: 'Hy Lạp', flag: '🇬🇷' },
  { value: 'Hong Kong', vi: 'Hồng Kông', flag: '🇭🇰' },
  { value: 'Hungary', vi: 'Hungary', flag: '🇭🇺' },
  { value: 'India', vi: 'Ấn Độ', flag: '🇮🇳' },
  { value: 'Indonesia', vi: 'Indonesia', flag: '🇮🇩' },
  { value: 'Ireland', vi: 'Ireland', flag: '🇮🇪' },
  { value: 'Israel', vi: 'Israel', flag: '🇮🇱' },
  { value: 'Italy', vi: 'Ý', flag: '🇮🇹' },
  { value: 'Japan', vi: 'Nhật Bản', flag: '🇯🇵' },
  { value: 'Laos', vi: 'Lào', flag: '🇱🇦' },
  { value: 'Malaysia', vi: 'Malaysia', flag: '🇲🇾' },
  { value: 'Mexico', vi: 'Mexico', flag: '🇲🇽' },
  { value: 'Myanmar', vi: 'Myanmar', flag: '🇲🇲' },
  { value: 'Nepal', vi: 'Nepal', flag: '🇳🇵' },
  { value: 'Netherlands', vi: 'Hà Lan', flag: '🇳🇱' },
  { value: 'New Zealand', vi: 'New Zealand', flag: '🇳🇿' },
  { value: 'Nigeria', vi: 'Nigeria', flag: '🇳🇬' },
  { value: 'Norway', vi: 'Na Uy', flag: '🇳🇴' },
  { value: 'Pakistan', vi: 'Pakistan', flag: '🇵🇰' },
  { value: 'Peru', vi: 'Peru', flag: '🇵🇪' },
  { value: 'Philippines', vi: 'Philippines', flag: '🇵🇭' },
  { value: 'Poland', vi: 'Ba Lan', flag: '🇵🇱' },
  { value: 'Portugal', vi: 'Bồ Đào Nha', flag: '🇵🇹' },
  { value: 'Romania', vi: 'Romania', flag: '🇷🇴' },
  { value: 'Russia', vi: 'Nga', flag: '🇷🇺' },
  { value: 'Saudi Arabia', vi: 'Ả Rập Xê Út', flag: '🇸🇦' },
  { value: 'Singapore', vi: 'Singapore', flag: '🇸🇬' },
  { value: 'South Africa', vi: 'Nam Phi', flag: '🇿🇦' },
  { value: 'South Korea', vi: 'Hàn Quốc', flag: '🇰🇷' },
  { value: 'Spain', vi: 'Tây Ban Nha', flag: '🇪🇸' },
  { value: 'Sri Lanka', vi: 'Sri Lanka', flag: '🇱🇰' },
  { value: 'Sweden', vi: 'Thụy Điển', flag: '🇸🇪' },
  { value: 'Switzerland', vi: 'Thụy Sĩ', flag: '🇨🇭' },
  { value: 'Taiwan', vi: 'Đài Loan', flag: '🇹🇼' },
  { value: 'Thailand', vi: 'Thái Lan', flag: '🇹🇭' },
  { value: 'Turkey', vi: 'Thổ Nhĩ Kỳ', flag: '🇹🇷' },
  { value: 'Ukraine', vi: 'Ukraine', flag: '🇺🇦' },
  { value: 'United Arab Emirates', vi: 'UAE', flag: '🇦🇪' },
  { value: 'United Kingdom', vi: 'Anh', flag: '🇬🇧' },
  { value: 'United States', vi: 'Mỹ', flag: '🇺🇸' },
  { value: 'Vietnam', vi: 'Việt Nam', flag: '🇻🇳' },
] as const;

export type CountryValue = (typeof COUNTRIES)[number]['value'];
