import {
  type ConstructedRow,
  NIN_SNAPSHOT_DATE,
  NIN_SOURCE_CODE,
  NIN_SOURCE_NAME,
} from './nin-types';

export const NIN_MIGRATION_PATH =
  'supabase/migrations/20260812100213_nin_foods_enrichment.sql';

interface MigrationMetadata {
  snapshotSha256: string;
  pullDate: string;
  counts: {
    loaded: number;
    quarantined: number;
    cloneRowsDropped: number;
    bowlsExcluded: number;
    vietnameseDuplicates: number;
    constructed: number;
  };
}

function sqlText(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlNumber(value: number | null): string {
  return value === null ? 'NULL' : String(value);
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return 'ARRAY[]::text[]';
  return `ARRAY[${values.map(sqlText).join(', ')}]::text[]`;
}

function compareIds(left: ConstructedRow, right: ConstructedRow): number {
  if (left.id < right.id) return -1;
  if (left.id > right.id) return 1;
  return 0;
}

function renderRow(row: ConstructedRow): string {
  return `INSERT INTO "vietnamese_food_composition" (
  "id", "name_primary", "name_alt", "name_en", "type_vn", "type_en",
  "source_id", "state", "calories_kcal", "protein_g", "carbohydrate_g",
  "fat_g", "fiber_g", "last_verified"
) VALUES (
  ${sqlText(row.id)}, ${sqlText(row.namePrimary)}, ${sqlTextArray(row.nameAlt)},
  ${sqlText(row.nameEn)}, ${sqlText(row.typeVn)}, ${sqlText(row.typeEn)},
  (SELECT "id" FROM "ingredient_sources" WHERE "code" = ${sqlText(NIN_SOURCE_CODE)}),
  ${sqlText(row.state)}, ${sqlNumber(row.caloriesKcal)},
  ${sqlNumber(row.proteinG)}, ${sqlNumber(row.carbohydrateG)},
  ${sqlNumber(row.fatG)}, ${sqlNumber(row.fiberG)}, DATE '${NIN_SNAPSHOT_DATE}'
)
ON CONFLICT ("id") DO NOTHING;`;
}

export function renderNinMigration(
  rows: ConstructedRow[],
  metadata: MigrationMetadata
): string {
  if (rows.length !== metadata.counts.constructed) {
    throw new Error(
      `Migration row count ${rows.length} does not match constructed count ${metadata.counts.constructed}`
    );
  }

  const counts = metadata.counts;
  const header = `SET search_path TO public, extensions;

-- NIN foods enrichment generated by scripts/enrich/nin-ingest.ts.
-- Snapshot SHA-256: ${metadata.snapshotSha256}
-- Pull date: ${metadata.pullDate}
-- Filters: ${counts.loaded} loaded - ${counts.quarantined} quarantined
--   - ${counts.cloneRowsDropped} clone rows - ${counts.bowlsExcluded} bowls
--   - ${counts.vietnameseDuplicates} Vietnamese duplicates
--   = ${counts.constructed} constructed rows (${counts.loaded}->${counts.constructed}).
-- Decisions and provenance: docs/NIN_ENRICHMENT.md
-- Embeddings are intentionally omitted: they are derived from an external API,
-- not deterministic migration data. Run the documented --embed backfill after
-- applying this migration.

INSERT INTO "ingredient_sources" ("code", "name") VALUES (
  ${sqlText(NIN_SOURCE_CODE)},
  ${sqlText(NIN_SOURCE_NAME)}
)
ON CONFLICT ("code") DO NOTHING;`;

  return `${header}\n\n${[...rows]
    .sort(compareIds)
    .map(renderRow)
    .join('\n\n')}\n`;
}
