/// The Koboyo cast behind every error / empty / 404 / offline surface: one
/// animal per area, the pose carrying the state, and a sleeping pose that wins
/// outright between 22:00 and 05:00. Twin of the web `lib/brand/illustrations/
/// cast.ts` — keep the two tables identical.
///
/// The art lives in `assets/illustrations/<slug>.svg` (generated by
/// `scripts/assets/gen-illustrations.mjs`); render it through
/// `shared/widgets/brand/surface_illustration.dart`, never by hand.
library;

/// The surfaces of the app, each with its own animal.
enum SurfaceArea { circle, logging, nutrition, dashboard, system }

/// What the surface is saying. An area that has no pose for a kind falls back
/// to its `empty` pose.
enum SurfaceKind { error, empty, emptyAlt, notFound, offline }

const String illustrationAssetDir = 'assets/illustrations';

const Map<SurfaceArea, Map<SurfaceKind, String>> _poses = {
  SurfaceArea.circle: {
    SurfaceKind.error: 'capybara-stuck-jar',
    SurfaceKind.empty: 'capybara-telescope',
    SurfaceKind.emptyAlt: 'capybara-peeking-out-box',
  },
  SurfaceArea.logging: {
    SurfaceKind.error: 'otter-tangled-string',
    SurfaceKind.empty: 'otter-peeking-out-box',
  },
  SurfaceArea.nutrition: {
    SurfaceKind.error: 'sloth-tangled-string',
    SurfaceKind.empty: 'sloth-peeking-out-box',
  },
  SurfaceArea.dashboard: {
    SurfaceKind.error: 'hedgehog-stuck-jar',
    SurfaceKind.empty: 'hedgehog-peeking-out-box',
  },
  SurfaceArea.system: {
    SurfaceKind.error: 'seal-sweeping-broom',
    SurfaceKind.empty: 'seal-holding-map',
    SurfaceKind.notFound: 'seal-telescope',
    SurfaceKind.offline: 'seal-hammock',
  },
};

const Map<SurfaceArea, String> _nightPoses = {
  SurfaceArea.circle: 'capybara-sleeping-hammock',
  SurfaceArea.logging: 'otter-wrapped-blanket',
  SurfaceArea.nutrition: 'sloth-sleeping-hammock',
  SurfaceArea.dashboard: 'hedgehog-napping-shoe',
  SurfaceArea.system: 'seal-curled-up-asleep',
};

/// The bundled SVG for [area] × [kind]. Night wins over the state: after 22:00
/// every surface shows its animal asleep, whatever went wrong.
String surfaceIllustrationAsset(
  SurfaceArea area,
  SurfaceKind kind, {
  required bool lateNight,
}) {
  final slug = lateNight
      ? _nightPoses[area]!
      : (_poses[area]![kind] ?? _poses[area]![SurfaceKind.empty]!);
  return '$illustrationAssetDir/$slug.svg';
}
